// gate-check-cron.ts — Phase 1.5 gate daily check + Telegram push
// Sprint 1307: runs via PM2 cron at 08:00 daily
// Reads workspace/gates/phase1-5-gate.json (generated by generate-phase1-5-gate.ts)
// Pushes gate status to Telegram if attention needed (ON_TRACK still sends)

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import * as https from 'https';

const GATE_FILE = join('workspace', 'gates', 'phase1-5-gate.json');

interface GateData {
  date: string;
  days_remaining: number;
  urgency: string;
  urgency_signal: string;
  overall_pass: boolean;
  recommendation: string;
  raw: {
    posts_count: number;
    total_views: number;
    posts_remaining: number;
  };
}

function sendTelegram(text: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const token = process.env.KAEL_BOT_TOKEN || process.env.TELEGRAM_BOT_TOKEN;
    const chatId = process.env.OWNER_TELEGRAM_CHAT_ID;
    if (!token || !chatId) {
      console.log('[gate-check] TELEGRAM_BOT_TOKEN or OWNER_TELEGRAM_CHAT_ID not set — skipping send');
      console.log('[gate-check] Message:\n' + text);
      resolve();
      return;
    }
    const body = JSON.stringify({ chat_id: chatId, text, parse_mode: 'HTML' });
    const req = https.request(
      {
        hostname: 'api.telegram.org',
        path: `/bot${token}/sendMessage`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) },
      },
      (res) => {
        let data = '';
        res.on('data', (chunk) => { data += chunk; });
        res.on('end', () => {
          const parsed = JSON.parse(data);
          if (!parsed.ok) {
            console.error('[gate-check] Telegram error:', parsed.description);
            reject(new Error(parsed.description));
          } else {
            resolve();
          }
        });
      }
    );
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

function urgencyEmoji(urgency: string): string {
  if (urgency === 'CRITICAL') return '🔴';
  if (urgency === 'HIGH') return '🟠';
  if (urgency === 'ON_TRACK') return '🟡';
  return '🟢';
}

async function main(): Promise<void> {
  if (!existsSync(GATE_FILE)) {
    console.log('[gate-check] Gate file not found:', GATE_FILE, '— skipping');
    process.exit(0);
  }

  const gate: GateData = JSON.parse(readFileSync(GATE_FILE, 'utf8'));
  const emoji = urgencyEmoji(gate.urgency);
  const passStr = gate.overall_pass ? '✅ PASS' : '❌ FAIL';
  const postsNeeded = gate.raw.posts_remaining ?? (30 - gate.raw.posts_count);

  const msg = [
    `${emoji} <b>Phase 1.5 Gate — ${gate.date}</b>`,
    `Posts: <b>${gate.raw.posts_count}/30</b> | Views: ${gate.raw.total_views} | Days left: <b>${gate.days_remaining}</b>`,
    `Status: ${passStr} — ${gate.urgency}`,
    `Need: ${postsNeeded} more posts (${(postsNeeded / Math.max(gate.days_remaining, 1)).toFixed(1)}/day)`,
    `💬 ${gate.recommendation}`,
  ].join('\n');

  console.log('[gate-check] Sending gate status to Telegram...');
  await sendTelegram(msg);
  console.log('[gate-check] Done.');
  process.exit(gate.overall_pass ? 0 : 1);
}

main().catch((err) => {
  console.error('[gate-check] Fatal:', err.message);
  process.exit(1);
});
