/**
 * ia-srt-fetcher.ts
 * Downloads the Internet Archive ASR subtitle file and parses it into timestamped segments.
 * IA runs auto-ASR on most videos — .asr.srt is free and already available.
 */

export interface SrtSegment {
  index: number;
  start: number;  // seconds (float)
  end: number;    // seconds (float)
  text: string;
}

/** Parse SRT timestamp "00:01:23,456" → 83.456 */
function parseSrtTime(ts: string): number {
  const [hms, ms] = ts.split(',');
  const [h, m, s] = hms.split(':').map(Number);
  return h * 3600 + m * 60 + s + (parseInt(ms ?? '0', 10) / 1000);
}

/** Strip HTML tags and normalize whitespace */
function cleanText(t: string): string {
  return t.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
}

/** Parse raw SRT string into SrtSegment[] */
function parseSrt(raw: string): SrtSegment[] {
  const blocks = raw.trim().split(/\n\s*\n/);
  const segments: SrtSegment[] = [];
  for (const block of blocks) {
    const lines = block.trim().split('\n');
    if (lines.length < 2) continue;
    const indexLine = lines[0].trim();
    const timeLine = lines[1];
    const textLines = lines.slice(2);
    const timeMatch = timeLine?.match(/(\d{2}:\d{2}:\d{2}[,.:]\d{3})\s+-->\s+(\d{2}:\d{2}:\d{2}[,.:]\d{3})/);
    if (!timeMatch) continue;
    const text = cleanText(textLines.join(' '));
    if (!text) continue;
    segments.push({
      index: parseInt(indexLine, 10) || segments.length + 1,
      start: parseSrtTime(timeMatch[1].replace('.', ',')),
      end: parseSrtTime(timeMatch[2].replace('.', ',')),
      text,
    });
  }
  return segments;
}

/** Downloads and parses the best available SRT for an IA identifier. */
export async function fetchSRT(identifier: string): Promise<SrtSegment[]> {
  // Fetch metadata to find SRT files
  const res = await fetch(`https://archive.org/metadata/${identifier}`);
  if (!res.ok) throw new Error(`IA metadata fetch failed: ${res.status}`);
  const data = await res.json() as { files?: Array<Record<string, string>> };
  const files = data.files ?? [];

  // Priority: .asr.srt > .autogenerated.asr.srt > any .srt
  const srtFiles = files.filter(f => f.name?.toLowerCase().endsWith('.srt'));
  const preferred =
    srtFiles.find(f => f.name?.includes('.asr.srt') && !f.name?.includes('autogenerated')) ??
    srtFiles.find(f => f.name?.includes('.asr.srt')) ??
    srtFiles.find(f => f.name?.includes('autogenerated')) ??
    srtFiles[0];

  if (!preferred) return [];

  const url = `https://archive.org/download/${identifier}/${preferred.name}`;
  const srtRes = await fetch(url);
  if (!srtRes.ok) return [];
  const raw = await srtRes.text();
  return parseSrt(raw);
}

/** Returns a plain transcript string (for sending to Claude) */
export function transcriptText(segments: SrtSegment[]): string {
  return segments.map(s => `[${s.start.toFixed(0)}s] ${s.text}`).join('\n');
}

/** Filters segments to [startSec, startSec+durationSec] and offsets timestamps to 0-based */
export function windowSegments(segments: SrtSegment[], startSec: number, durationSec: number): SrtSegment[] {
  const end = startSec + durationSec;
  return segments
    .filter(s => s.end > startSec && s.start < end)
    .map((s, i) => ({
      index: i + 1,
      start: Math.max(0, s.start - startSec),
      end: Math.min(durationSec, s.end - startSec),
      text: s.text,
    }));
}
