/**
 * seed-video-sources.ts
 * Inserts all 50 open video sources from the viral agent reference doc.
 * Run AFTER creating the table with video-sources-migration.sql.
 *
 * Usage:  tsx src/seed-video-sources.ts
 */

import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';
import { resolve } from 'path';

config({ path: resolve(process.env.HOME ?? '/Users/tarekmnif', 'kognai', '.env'), override: true });

const db = createClient(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_ANON_KEY!,
);

interface VideoSource {
  name: string;
  url: string;
  category: string;
  license: string;
  api_available: boolean;
  api_url?: string;
  api_docs?: string;
  api_key_required: boolean;
  rate_limits?: string;
  content_types: string[];
  agent_notes: string;
  commercial_use: boolean;
  attribution_required: boolean;
  tier: number;
  best_content_type: string;
}

const SOURCES: VideoSource[] = [
  // ── CATEGORY 1: GOVERNMENT ARCHIVES ─────────────────────────────────
  {
    name: 'Internet Archive — Moving Image',
    url: 'https://archive.org/details/movies',
    category: 'government_archive',
    license: 'mixed',
    api_available: true,
    api_url: 'https://archive.org/advancedsearch.php',
    api_docs: 'https://archive.org/developers/index-apis.html',
    api_key_required: false,
    rate_limits: '1 req/sec recommended',
    content_types: ['historical_films', 'newsreels', 'educational', 'silent_films', 'animation', 'documentaries', 'government_films'],
    agent_notes: 'Primary source. Use mediatype:movies + licenseurl filter. Prelinger sub-collection is entirely public domain. Rich metadata including subject, date, creator, license.',
    commercial_use: true,
    attribution_required: false,
    tier: 1,
    best_content_type: 'Historical, archival',
  },
  {
    name: 'Prelinger Archives',
    url: 'https://archive.org/details/prelinger',
    category: 'government_archive',
    license: 'public_domain',
    api_available: true,
    api_url: 'https://archive.org/advancedsearch.php?q=collection:prelinger',
    api_docs: 'https://archive.org/developers/index-apis.html',
    api_key_required: false,
    rate_limits: '1 req/sec recommended',
    content_types: ['advertising_films', 'educational_films', 'industrial_films', 'home_movies', 'propaganda', 'social_guidance'],
    agent_notes: 'Entirely public domain — no license check needed. 60,000+ ephemeral films 1927–1987. Exceptional for vintage aesthetics and retro viral formats. Some 4K/5K ProRes scans.',
    commercial_use: true,
    attribution_required: false,
    tier: 1,
    best_content_type: 'Vintage, cultural',
  },
  {
    name: 'NASA Image and Video Library',
    url: 'https://images.nasa.gov',
    category: 'government_archive',
    license: 'public_domain',
    api_available: true,
    api_url: 'https://images-api.nasa.gov/search',
    api_docs: 'https://api.nasa.gov/',
    api_key_required: true,
    rate_limits: '1,000 req/hr with key; 30 req/hr without',
    content_types: ['space_launches', 'ISS', 'spacewalks', 'earth_from_space', 'mars_rover', 'hubble', 'james_webb', 'astronauts', 'mission_control', 'solar_events'],
    agent_notes: 'Single best source for awe-inspiring space content. 100% public domain. API returns direct download URLs + rich metadata. NASA YouTube also has 4K videos via YouTube Data API. Pixabay hosts 165+ NASA 4K clips.',
    commercial_use: true,
    attribution_required: false,
    tier: 1,
    best_content_type: 'Space, science',
  },
  {
    name: 'NOAA Multimedia',
    url: 'https://www.noaa.gov/multimedia/videos',
    category: 'government_archive',
    license: 'public_domain',
    api_available: false,
    rate_limits: 'No hard limit',
    content_types: ['ocean_footage', 'marine_life', 'coral_reefs', 'deep_sea', 'hurricanes', 'weather', 'climate', 'fisheries'],
    agent_notes: 'Exceptional for ocean/weather content. Deep-sea exploration videos look like sci-fi — extremely viral. All public domain. Also on NOAA YouTube channel.',
    commercial_use: true,
    attribution_required: false,
    tier: 2,
    best_content_type: 'Ocean, weather',
  },
  {
    name: 'USGS Multimedia Gallery',
    url: 'https://www.usgs.gov/products/multimedia-gallery/videos',
    category: 'government_archive',
    license: 'public_domain',
    api_available: false,
    content_types: ['volcanic_eruptions', 'earthquakes', 'landslides', 'geological_formations', 'satellite_imagery', 'wildlife_surveys', 'natural_disasters'],
    agent_notes: 'Excellent for extreme natural events. Lava flows and volcanic eruptions perform very well on TikTok. All public domain. Also on USGS YouTube channel.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Geology, disasters',
  },
  {
    name: 'Library of Congress — Film & Video',
    url: 'https://www.loc.gov/film-and-videos/',
    category: 'government_archive',
    license: 'mixed',
    api_available: true,
    api_url: 'https://www.loc.gov/api/',
    api_docs: 'https://www.loc.gov/apis/',
    api_key_required: true,
    content_types: ['historical_films', 'newsreels', 'oral_histories', 'early_cinema', 'government_films', 'cultural_documentation'],
    agent_notes: 'World\'s largest library. API returns JSON with direct media URLs. Particularly valuable for pre-1930 footage and early American cinema. "American Memory" collection is especially rich.',
    commercial_use: true,
    attribution_required: false,
    tier: 2,
    best_content_type: 'Historical',
  },
  {
    name: 'National Archives (NARA)',
    url: 'https://www.archives.gov/research/catalog',
    category: 'government_archive',
    license: 'public_domain',
    api_available: true,
    api_url: 'https://catalog.archives.gov/api/v2/',
    api_docs: 'https://www.archives.gov/research/catalog/help/api',
    api_key_required: false,
    content_types: ['WWII_footage', 'government_newsreels', 'presidential', 'military_operations', 'historical_events', 'space_program'],
    agent_notes: 'Official US government archive. Rare WWII footage, presidential recordings, historical government films. API provides metadata + download links for digitized items.',
    commercial_use: true,
    attribution_required: false,
    tier: 2,
    best_content_type: 'Government, WWII',
  },
  {
    name: 'NASA GIBS — Earth Satellite Imagery',
    url: 'https://www.earthdata.nasa.gov/engage/open-data-services-software/earthdata-developer-portal/gibs-api',
    category: 'government_archive',
    license: 'public_domain',
    api_available: true,
    api_url: 'https://gibs.earthdata.nasa.gov',
    api_docs: 'https://www.earthdata.nasa.gov/engage/open-data-services-software/earthdata-developer-portal/gibs-api',
    api_key_required: false,
    content_types: ['satellite_imagery', 'earth_timelapse', 'natural_disasters_from_space', 'climate_visualizations'],
    agent_notes: 'OGC-compliant API for global satellite imagery. Can be assembled into time-lapse videos. Useful for Earth-from-space awe content.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Earth, satellite',
  },
  {
    name: 'White House YouTube Channel',
    url: 'https://www.youtube.com/@WhiteHouse',
    category: 'government_archive',
    license: 'public_domain',
    api_available: true,
    api_url: 'https://www.googleapis.com/youtube/v3/',
    api_docs: 'https://developers.google.com/youtube/v3/',
    api_key_required: true,
    content_types: ['presidential_addresses', 'press_briefings', 'official_ceremonies', 'policy_announcements', 'historical_footage'],
    agent_notes: 'All White House official content is public domain. Accessible via YouTube Data API using channel ID UCnniqWGq9lOqYd5sGWxVi7w.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Politics, history',
  },

  // ── CATEGORY 2: STOCK FOOTAGE ────────────────────────────────────────
  {
    name: 'Pexels Videos',
    url: 'https://www.pexels.com/videos/',
    category: 'stock_footage',
    license: 'pexels',
    api_available: true,
    api_url: 'https://api.pexels.com/videos/search',
    api_docs: 'https://www.pexels.com/api/documentation/',
    api_key_required: true,
    rate_limits: '200 req/hr, 20,000 req/month',
    content_types: ['lifestyle', 'nature', 'urban', 'food', 'people', 'travel', 'business', 'animals', 'abstract'],
    agent_notes: 'Best free stock video API. Returns JSON with direct download URLs (SD/HD/4K). Supports keyword search + orientation=portrait for vertical. No attribution required for commercial use.',
    commercial_use: true,
    attribution_required: false,
    tier: 1,
    best_content_type: 'Contemporary',
  },
  {
    name: 'Pixabay Videos',
    url: 'https://pixabay.com/videos/',
    category: 'stock_footage',
    license: 'pixabay',
    api_available: true,
    api_url: 'https://pixabay.com/api/videos/',
    api_docs: 'https://pixabay.com/api/docs/',
    api_key_required: true,
    rate_limits: '100 req/min',
    content_types: ['nature', 'space', 'animals', 'abstract', 'technology', 'food', 'people', 'timelapse', '4K'],
    agent_notes: '3M+ videos. API returns direct CDN download URLs (large/medium/small/tiny). Strong for nature, space (NASA clips), abstract. Note: mass auto-downloading violates ToS — pull on demand and cache.',
    commercial_use: true,
    attribution_required: false,
    tier: 1,
    best_content_type: 'Nature, abstract',
  },
  {
    name: 'Coverr',
    url: 'https://coverr.co',
    category: 'stock_footage',
    license: 'coverr',
    api_available: true,
    api_url: 'https://coverr.co/api',
    api_docs: 'https://coverr.co/api',
    api_key_required: true,
    rate_limits: '1,000 calls/month',
    content_types: ['lifestyle', 'nature', 'urban', 'food', 'travel', 'abstract', 'people'],
    agent_notes: 'Smaller but extremely high-quality curated library. Most permissive license of any stock platform — truly no restrictions. Best for high-quality lifestyle and nature B-roll.',
    commercial_use: true,
    attribution_required: false,
    tier: 2,
    best_content_type: 'Lifestyle, nature',
  },
  {
    name: 'Mixkit',
    url: 'https://mixkit.co/free-stock-video/',
    category: 'stock_footage',
    license: 'mixkit',
    api_available: false,
    content_types: ['lifestyle', 'nature', 'urban', 'food', 'business', 'abstract', 'vertical_4K'],
    agent_notes: 'No API but direct download without account. Very permissive license. Particularly useful for vertical 9:16 content for TikTok/Reels. Download URLs follow predictable pattern.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Lifestyle, vertical',
  },
  {
    name: 'Videezy',
    url: 'https://www.videezy.com',
    category: 'stock_footage',
    license: 'videezy_standard',
    api_available: false,
    content_types: ['nature', 'urban', 'abstract', 'technology', 'people', 'timelapse', 'aerial'],
    agent_notes: '100K+ videos. Attribution required for free tier. Good for aerial and drone footage. No API.',
    commercial_use: true,
    attribution_required: true,
    tier: 3,
    best_content_type: 'Aerial, nature',
  },
  {
    name: 'Videvo',
    url: 'https://www.videvo.net',
    category: 'stock_footage',
    license: 'mixed',
    api_available: false,
    content_types: ['nature', 'urban', 'abstract', 'people', 'technology', 'timelapse', 'motion_graphics'],
    agent_notes: '300K+ clips with mixed licensing. Always check per-clip license. CC BY 3.0 clips require attribution; Videvo Standard clips are free commercial. No API.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Nature, urban',
  },
  {
    name: 'SplitShire',
    url: 'https://www.splitshire.com/videos',
    category: 'stock_footage',
    license: 'royalty_free',
    api_available: false,
    content_types: ['lifestyle', 'nature', 'urban', 'food', 'people'],
    agent_notes: 'Small but high-quality curated collection. No restrictions on commercial use. No attribution required. No API.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Artistic, lifestyle',
  },
  {
    name: 'Mazwai',
    url: 'https://mazwai.com',
    category: 'stock_footage',
    license: 'cc_by',
    api_available: false,
    content_types: ['cinematic_nature', 'urban', 'landscape', 'aerial'],
    agent_notes: 'High-quality cinematic footage. Attribution required (CC BY 3.0). No API. Best for premium-looking B-roll.',
    commercial_use: true,
    attribution_required: true,
    tier: 3,
    best_content_type: 'Cinematic',
  },
  {
    name: 'Pond5 — Public Domain Project',
    url: 'https://www.pond5.com/public-domain',
    category: 'stock_footage',
    license: 'public_domain',
    api_available: true,
    api_docs: 'https://www.pond5.com/developer',
    api_key_required: true,
    content_types: ['historic_film', 'archival_clips', 'vintage_animation', 'historical_events', 'nature'],
    agent_notes: 'Curated public domain collection. Free account required for download. Broader Pond5 library requires paid subscription but PD section is free. Valuable for historical/archival content.',
    commercial_use: true,
    attribution_required: false,
    tier: 2,
    best_content_type: 'Historical',
  },
  {
    name: 'Life of Vids',
    url: 'https://lifeofvids.com',
    category: 'stock_footage',
    license: 'cc0',
    api_available: false,
    content_types: ['urban', 'nature', 'lifestyle', 'people', 'food'],
    agent_notes: 'Small but entirely CC0. No restrictions. Direct download.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Urban, lifestyle',
  },
  {
    name: 'Dareful',
    url: 'https://dareful.com',
    category: 'stock_footage',
    license: 'cc_by',
    api_available: false,
    content_types: ['4K_cinematic', 'aerial', 'urban', 'abstract'],
    agent_notes: 'High-quality 4K footage. CC BY 4.0 — attribution required. Direct download.',
    commercial_use: true,
    attribution_required: true,
    tier: 3,
    best_content_type: '4K cinematic',
  },
  {
    name: 'Freepik Videos',
    url: 'https://www.freepik.com/videos',
    category: 'stock_footage',
    license: 'freepik',
    api_available: true,
    api_docs: 'https://docs.freepik.com/',
    api_key_required: true,
    content_types: ['lifestyle', 'business', 'nature', 'food', 'people', 'abstract'],
    agent_notes: '100K+ videos. Free tier requires attribution. API available for programmatic access.',
    commercial_use: true,
    attribution_required: true,
    tier: 3,
    best_content_type: 'Contemporary',
  },

  // ── CATEGORY 3: CREATIVE COMMONS REPOSITORIES ────────────────────────
  {
    name: 'Wikimedia Commons — Videos',
    url: 'https://commons.wikimedia.org/wiki/Category:Videos',
    category: 'creative_commons',
    license: 'mixed',
    api_available: true,
    api_url: 'https://commons.wikimedia.org/w/api.php',
    api_docs: 'https://commons.wikimedia.org/wiki/Commons:API',
    api_key_required: false,
    rate_limits: '500 req/10min anonymous',
    content_types: ['nature', 'science', 'history', 'culture', 'sports', 'wildlife', 'space', 'animation', 'educational'],
    agent_notes: 'World\'s largest free media repository. MediaWiki API: action=query&list=categorymembers&cmtype=file&cmtitle=Category:Videos. Filter for CC0 and CC BY for maximum freedom.',
    commercial_use: true,
    attribution_required: false,
    tier: 1,
    best_content_type: 'All categories',
  },
  {
    name: 'Vimeo Creative Commons',
    url: 'https://vimeo.com/creativecommons',
    category: 'creative_commons',
    license: 'mixed',
    api_available: true,
    api_url: 'https://api.vimeo.com/videos',
    api_docs: 'https://developer.vimeo.com/api/reference/videos',
    api_key_required: true,
    rate_limits: '250 API calls/day (Basic tier)',
    content_types: ['short_films', 'documentaries', 'nature', 'art', 'music_videos', 'experimental', 'animation', 'lifestyle'],
    agent_notes: 'Massive CC-licensed collection. API filter=CC for license filtering. Focus on CC BY and CC BY-SA for commercial remixing. NIST V3C1 dataset has 7,475 Vimeo CC videos pre-compiled.',
    commercial_use: true,
    attribution_required: false,
    tier: 2,
    best_content_type: 'Art, documentary',
  },
  {
    name: 'Flickr Creative Commons Videos',
    url: 'https://www.flickr.com/creativecommons',
    category: 'creative_commons',
    license: 'mixed',
    api_available: true,
    api_docs: 'https://www.flickr.com/services/api/',
    api_key_required: true,
    content_types: ['amateur', 'professional', 'events', 'nature', 'travel', 'culture'],
    agent_notes: 'Flickr has significant volume of CC-licensed video. API supports license filtering. As of May 2025, Flickr restricts original-size downloads for free accounts — verify terms. Best for CC BY and CC0.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Amateur, events',
  },
  {
    name: 'Open Images (Open Beelden) — Netherlands',
    url: 'https://www.openbeelden.nl',
    category: 'creative_commons',
    license: 'cc_by',
    api_available: true,
    api_url: 'https://www.openbeelden.nl/api',
    api_docs: 'https://www.openbeelden.nl/api',
    api_key_required: false,
    content_types: ['dutch_cultural_history', 'news_footage', 'documentaries', 'nature', 'social_history', 'art'],
    agent_notes: 'Netherlands Institute for Sound and Vision. OAI-PMH formatted metadata with download links. Primarily Dutch-language but visually usable for any audience.',
    commercial_use: true,
    attribution_required: true,
    tier: 3,
    best_content_type: 'Dutch cultural',
  },
  {
    name: 'YouTube — Creative Commons Filter',
    url: 'https://www.youtube.com',
    category: 'creative_commons',
    license: 'cc_by',
    api_available: true,
    api_url: 'https://www.googleapis.com/youtube/v3/search?videoLicense=creativeCommon',
    api_docs: 'https://developers.google.com/youtube/v3/',
    api_key_required: true,
    rate_limits: '10,000 units/day free; search costs 100 units',
    content_types: ['educational', 'nature', 'science', 'history', 'music', 'sports', 'comedy', 'news'],
    agent_notes: 'Filter by videoLicense=creativeCommon in Search API. Returns CC BY 3.0 videos — attribution required. Verify uploader had rights before relying on CC label. Use yt-dlp for confirmed CC content only.',
    commercial_use: true,
    attribution_required: true,
    tier: 2,
    best_content_type: 'All categories',
  },
  {
    name: 'European Southern Observatory (ESO) Videos',
    url: 'https://www.eso.org/public/videos/',
    category: 'creative_commons',
    license: 'cc_by',
    api_available: false,
    content_types: ['space', 'astronomy', 'telescopes', 'stars', 'galaxies', 'nebulae', 'night_sky_timelapse', 'ultra_HD_space'],
    agent_notes: 'Some of the most stunning space footage available. CC BY 4.0. Ultra-HD time-lapses of Atacama Desert and deep space. Available in 4K and 8K. Attribution to ESO required.',
    commercial_use: true,
    attribution_required: true,
    tier: 3,
    best_content_type: 'Space, astronomy',
  },

  // ── CATEGORY 4: SCIENTIFIC & INSTITUTIONAL ───────────────────────────
  {
    name: 'NIH / NCI Visuals Online',
    url: 'https://visualsonline.cancer.gov',
    category: 'scientific',
    license: 'public_domain',
    api_available: false,
    content_types: ['biomedical_animations', 'cancer_cell_footage', 'medical_procedures', 'microscopy', 'scientific_visualizations'],
    agent_notes: 'Public domain biomedical imagery and video. Most items labeled "Public Domain". Valuable for science and health content niches.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Biomedical',
  },
  {
    name: 'NIH / PubMed Central Open Access Videos',
    url: 'https://www.ncbi.nlm.nih.gov/pmc/',
    category: 'scientific',
    license: 'mixed',
    api_available: true,
    api_url: 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/',
    api_docs: 'https://www.ncbi.nlm.nih.gov/home/develop/api/',
    api_key_required: false,
    content_types: ['research_videos', 'microscopy', 'biological_processes', 'medical_procedures', 'experimental_demonstrations'],
    agent_notes: 'Scientific papers in PMC often include CC BY supplementary video files. E-utilities API can search for papers with video supplements. Microscopy and biological process content.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Science, medical',
  },
  {
    name: 'Wellcome Collection — Moving Image Archive',
    url: 'https://wellcomecollection.org',
    category: 'scientific',
    license: 'mixed',
    api_available: true,
    api_docs: 'https://developers.wellcomecollection.org/',
    api_key_required: false,
    content_types: ['history_of_medicine', 'surgery', 'mental_health', 'public_health', 'pharmaceutical_films'],
    agent_notes: 'Major UK medical charity archive. Many CC BY licensed films. Also accessible via Internet Archive at archive.org/details/wellcomefilm.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Medical history',
  },
  {
    name: 'Smithsonian Institution Open Access',
    url: 'https://www.si.edu/openaccess',
    category: 'scientific',
    license: 'cc0',
    api_available: true,
    api_url: 'https://edan.si.edu/openaccess/api/v2/search',
    api_docs: 'https://edan.si.edu/openaccess/apidocs/',
    api_key_required: false,
    content_types: ['natural_history', 'cultural_artifacts', 'art', 'science', 'american_history', 'space_exploration'],
    agent_notes: 'Millions of CC0 items including videos. API supports full-text search and returns direct media URLs. Particularly valuable for natural history and cultural content.',
    commercial_use: true,
    attribution_required: false,
    tier: 2,
    best_content_type: 'Natural history',
  },
  {
    name: 'USDA Video Library',
    url: 'https://www.usda.gov/media/video',
    category: 'scientific',
    license: 'public_domain',
    api_available: false,
    content_types: ['agriculture', 'food_production', 'nature', 'wildlife', 'forests', 'rural_america'],
    agent_notes: 'All USDA content is public domain. American landscapes, farming, wildlife, food production. Also on USDA YouTube channel.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Agriculture, nature',
  },
  {
    name: 'NASA Goddard SVS — Scientific Visualization',
    url: 'https://svs.gsfc.nasa.gov',
    category: 'scientific',
    license: 'public_domain',
    api_available: false,
    content_types: ['scientific_visualizations', 'climate_animations', 'space_weather', 'earth_system_models', 'planetary_science'],
    agent_notes: 'Stunning scientific animations of Earth and space phenomena. All public domain. Climate, weather, and space science content that performs extremely well on TikTok.',
    commercial_use: true,
    attribution_required: false,
    tier: 2,
    best_content_type: 'Scientific viz',
  },
  {
    name: 'NASA JPL Videos',
    url: 'https://www.jpl.nasa.gov/videos',
    category: 'scientific',
    license: 'public_domain',
    api_available: false,
    content_types: ['mars_missions', 'spacecraft', 'planetary_science', 'solar_system', 'mission_animations'],
    agent_notes: 'JPL mission footage and scientific animations. All public domain. Particularly valuable for Mars and deep space content.',
    commercial_use: true,
    attribution_required: false,
    tier: 2,
    best_content_type: 'Planetary science',
  },
  {
    name: 'ESA Media — European Space Agency',
    url: 'https://www.esa.int/ESA_Multimedia/Videos',
    category: 'scientific',
    license: 'cc_by_sa',
    api_available: false,
    content_types: ['space_missions', 'earth_observation', 'astronauts', 'rockets', 'satellites', 'ISS'],
    agent_notes: 'CC BY-SA 3.0 IGO. Attribution + share-alike required. High-quality space footage complementary to NASA. Derivative works must use same license.',
    commercial_use: true,
    attribution_required: true,
    tier: 3,
    best_content_type: 'Space missions',
  },
  {
    name: 'Hubble Space Telescope (STScI)',
    url: 'https://hubblesite.org/resource-gallery/videos',
    category: 'scientific',
    license: 'public_domain',
    api_available: false,
    content_types: ['deep_space', 'galaxy_formations', 'nebulae', 'cosmic_events', 'scientific_visualizations'],
    agent_notes: 'Hubble imagery and videos as public domain. Some of the most visually stunning content available. Complementary to NASA Image Library.',
    commercial_use: true,
    attribution_required: false,
    tier: 2,
    best_content_type: 'Deep space',
  },

  // ── CATEGORY 5: NEWS & DOCUMENTARY ──────────────────────────────────
  {
    name: 'AP Archive (YouTube)',
    url: 'https://www.youtube.com/@APArchive',
    category: 'news_documentary',
    license: 'embed_only',
    api_available: true,
    api_url: 'https://www.googleapis.com/youtube/v3/',
    api_key_required: true,
    content_types: ['historical_news_footage', 'world_events', 'politics', 'sports', 'entertainment', 'disasters'],
    agent_notes: 'Entire AP historical collection on YouTube. Freely embeddable — no license needed for embedding. For download/repurposing, AP license required. Pre-1928 footage is public domain.',
    commercial_use: false,
    attribution_required: true,
    tier: 3,
    best_content_type: 'News, history',
  },
  {
    name: 'British Pathé (YouTube)',
    url: 'https://www.youtube.com/@britishpathe',
    category: 'news_documentary',
    license: 'embed_only',
    api_available: true,
    api_url: 'https://www.googleapis.com/youtube/v3/',
    api_key_required: true,
    content_types: ['british_history', 'WWII', 'royalty', 'sports', 'entertainment', 'social_history', 'disasters'],
    agent_notes: '85,000+ films 1895–1970. Freely embeddable on YouTube. Pre-1928 content is PD in most jurisdictions. Dedicated search at britishpathe.com. Download licensing is paid.',
    commercial_use: false,
    attribution_required: true,
    tier: 3,
    best_content_type: 'Historical news',
  },
  {
    name: 'Al Jazeera Creative Commons Repository',
    url: 'https://archive.org/details/aljazeeracc',
    category: 'news_documentary',
    license: 'cc_by',
    api_available: true,
    api_url: 'https://archive.org/advancedsearch.php?q=collection:aljazeeracc',
    api_key_required: false,
    content_types: ['news_footage', 'journalism', 'middle_east', 'documentary'],
    agent_notes: 'World\'s first broadcast-quality CC news footage repository (2009). Via Internet Archive. Attribution to Al Jazeera required. Limited volume but historically significant.',
    commercial_use: true,
    attribution_required: true,
    tier: 3,
    best_content_type: 'News, journalism',
  },
  {
    name: 'GBH Open Vault (WGBH Boston)',
    url: 'https://openvault.wgbh.org',
    category: 'news_documentary',
    license: 'mixed',
    api_available: false,
    content_types: ['public_television', 'documentaries', 'news', 'cultural_programming', 'american_media'],
    agent_notes: 'Hundreds of thousands of WGBH/GBH programs. Many viewable online; download rights vary. Valuable for American cultural and historical documentary content.',
    commercial_use: false,
    attribution_required: true,
    tier: 3,
    best_content_type: 'Public TV, docs',
  },
  {
    name: 'Europeana',
    url: 'https://www.europeana.eu',
    category: 'news_documentary',
    license: 'mixed',
    api_available: true,
    api_url: 'https://api.europeana.eu/record/v2/search.json',
    api_docs: 'https://apis.europeana.eu/',
    api_key_required: true,
    content_types: ['european_cultural_heritage', 'art', 'history', 'film', 'music', 'photography'],
    agent_notes: '50M+ items from 3,000+ European institutions. API: use reusability=open to filter freely reusable content. Particularly valuable for European history and cultural content.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'European heritage',
  },
  {
    name: 'Open Culture — Free Movies',
    url: 'https://www.openculture.com/freemoviesonline',
    category: 'news_documentary',
    license: 'mixed',
    api_available: false,
    content_types: ['classic_films', 'documentaries', 'foreign_films', 'silent_films', 'noir', 'animation'],
    agent_notes: '4,000+ free movies curated from YouTube, IA, and other platforms. Not a direct source — a discovery tool. All linked content is legally free to watch; download rights depend on host.',
    commercial_use: false,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Classic films',
  },
  {
    name: 'WikiFlix',
    url: 'https://wikiflix.toolforge.org',
    category: 'news_documentary',
    license: 'mixed',
    api_available: true,
    api_url: 'https://commons.wikimedia.org/w/api.php',
    api_key_required: false,
    content_types: ['public_domain_films', 'silent_films', 'classic_cinema', 'documentaries', 'animation'],
    agent_notes: 'Wikimedia-powered streaming site for public domain films. 4,000+ films sourced from Wikimedia Commons. Launched January 2026.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Classic cinema',
  },

  // ── CATEGORY 6: SPECIALIZED & NICHE ─────────────────────────────────
  {
    name: 'CuteStockFootage',
    url: 'https://cutestockfootage.com',
    category: 'specialized',
    license: 'cc_by',
    api_available: false,
    content_types: ['video_transitions', 'light_leaks', 'particles', 'green_screen', 'video_backgrounds', 'overlays'],
    agent_notes: 'Motion graphics elements and overlays rather than footage. Useful for adding visual effects. CC BY 4.0 — attribution required.',
    commercial_use: true,
    attribution_required: true,
    tier: 3,
    best_content_type: 'Motion graphics',
  },
  {
    name: 'Beachfront B-Roll',
    url: 'https://archive.org/details/beachfrontbroll',
    category: 'specialized',
    license: 'royalty_free',
    api_available: true,
    api_url: 'https://archive.org/advancedsearch.php?q=collection:beachfrontbroll',
    api_key_required: false,
    content_types: ['HD_stock', 'timelapse', 'HDR_footage', 'animated_backgrounds'],
    agent_notes: 'Personal videographer release on Internet Archive. Royalty-free, free for commercial use. Inactive since 2016 but archive remains accessible and downloadable via IA API.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Time-lapse, HD',
  },
  {
    name: 'Free Stock Footage Archive',
    url: 'https://www.free-stock-footage.com',
    category: 'specialized',
    license: 'cc_by',
    api_available: false,
    content_types: ['glitch_footage', 'VHS_effects', 'analog_artifacts', 'abstract_visuals'],
    agent_notes: 'Specialized in glitch and analog aesthetic footage. Useful for retro or lo-fi visual effects. CC BY 3.0 — attribution required.',
    commercial_use: true,
    attribution_required: true,
    tier: 3,
    best_content_type: 'Glitch, analog',
  },
  {
    name: 'NIST V3C1 Dataset (Vimeo CC)',
    url: 'https://data.nist.gov/od/id/mds2-2542',
    category: 'specialized',
    license: 'mixed',
    api_available: true,
    api_url: 'https://data.nist.gov/od/id/mds2-2542',
    api_key_required: false,
    content_types: ['diverse_vimeo_cc'],
    agent_notes: '7,475 Vimeo CC videos (1.3 TB, 1,000 hours). Pre-compiled NIST research dataset. Bulk download. Useful for training or as a bulk source of diverse CC footage.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Diverse (research)',
  },
  {
    name: 'YFCC100M — Yahoo Flickr CC 100M',
    url: 'https://multimediacommons.wordpress.com/yfcc100m-core-dataset/',
    category: 'specialized',
    license: 'mixed',
    api_available: true,
    api_url: 'https://aws.amazon.com/marketplace/pp/prodview-yjzd2o4p7rl7m',
    api_key_required: false,
    content_types: ['amateur_video', 'travel', 'events', 'nature', 'urban', 'people'],
    agent_notes: 'Largest publicly available CC multimedia dataset. ~800K Flickr CC videos. Videos downloaded from Flickr using provided URLs. GitHub downloader: chi0tzp/YFCC100M-Downloader.',
    commercial_use: true,
    attribution_required: false,
    tier: 3,
    best_content_type: 'Amateur, diverse',
  },
  {
    name: 'Open Images Dataset (Google)',
    url: 'https://storage.googleapis.com/openimages/web/index.html',
    category: 'specialized',
    license: 'cc_by',
    api_available: true,
    api_url: 'https://storage.googleapis.com/openimages/web/download_v7.html',
    api_key_required: false,
    content_types: ['images', 'video_annotations'],
    agent_notes: 'Primarily images but includes video annotations useful for video understanding. CC BY 4.0 — attribution to Google required.',
    commercial_use: true,
    attribution_required: true,
    tier: 3,
    best_content_type: 'Images + annotations',
  },
  {
    name: 'Kinetics Dataset (DeepMind/Google)',
    url: 'https://www.deepmind.com/open-source/kinetics',
    category: 'specialized',
    license: 'cc_by',
    api_available: true,
    api_url: 'https://github.com/google-deepmind/kinetics-dataset',
    api_key_required: false,
    content_types: ['human_actions', 'sports', 'cooking', 'social_interactions'],
    agent_notes: 'YouTube video clips annotated for 650+ human action classes. Metadata is CC BY 4.0; individual videos subject to YouTube ToS. Useful for identifying types of human action footage on YouTube.',
    commercial_use: true,
    attribution_required: true,
    tier: 3,
    best_content_type: 'Human actions',
  },
];

async function seed() {
  console.log(`\n🌱 Seeding ${SOURCES.length} video sources...`);

  // Upsert in batches of 20 to avoid request size limits
  const BATCH = 20;
  let inserted = 0;
  let skipped = 0;

  for (let i = 0; i < SOURCES.length; i += BATCH) {
    const batch = SOURCES.slice(i, i + BATCH).map(s => ({
      ...s,
      api_key_required: s.api_key_required ?? false,
    }));
    const { data, error } = await db
      .from('video_sources')
      .upsert(batch, { onConflict: 'name', ignoreDuplicates: false })
      .select('name');

    if (error) {
      console.error(`  ✗ Batch ${Math.floor(i / BATCH) + 1} error:`, error.message);
      process.exit(1);
    }
    inserted += data?.length ?? 0;
    console.log(`  ✓ Batch ${Math.floor(i / BATCH) + 1}: ${data?.length ?? 0} sources`);
  }

  console.log(`\n✅ Done — ${inserted} sources seeded (${skipped} unchanged)`);

  // Quick sanity check
  const { count } = await db.from('video_sources').select('*', { count: 'exact', head: true });
  console.log(`📊 Total rows in video_sources: ${count}`);
}

seed().catch(err => { console.error('Fatal:', err); process.exit(1); });
