/**
 * viral-topics.ts
 * 30 ranked viral topics from viral_agent_report_EN.md (Section B)
 * Single source of truth for all IA scraper queries.
 */

export type MediaType = 'movies' | 'audio' | 'texts' | 'image';
export type ViralTrigger = 'awe' | 'shock' | 'amusement' | 'inspiration' | 'nostalgia' | 'curiosity' | 'satisfaction' | 'debate';
export type Platform = 'tiktok' | 'youtube_shorts' | 'instagram_reels';

export interface TopicConfig {
  id: string;
  rank: number;
  name: string;
  triggers: ViralTrigger[];
  ia_queries: string[];
  /** Search queries optimised for Pexels / Pixabay stock footage (Sprint-057). */
  stock_queries?: string[];
  mediatype: MediaType;
  ia_collection?: string;
  music_genre: string;
  caption_strategy: string;
  platform_priority: Platform[];
  min_score?: number;
}

export const VIRAL_TOPICS: TopicConfig[] = [
  {
    id: 'T01',
    rank: 1,
    name: 'Wildlife & Animal Predator/Prey Encounters',
    triggers: ['awe', 'shock'],
    ia_queries: ['wildlife predator prey hunt attack', 'cheetah lion tiger nature footage', 'animal attack wildlife documentary', 'shark whale orca predator ocean'],
    stock_queries: ['wildlife predator prey', 'lion tiger cheetah hunting', 'shark eagle animal attack nature'],
    mediatype: 'movies',
    music_genre: 'Cinematic orchestral, tension-building strings, dramatic percussion',
    caption_strategy: 'Single-line factual hook ("This spider can kill a bird in 3 seconds") + species name overlay',
    platform_priority: ['tiktok', 'youtube_shorts', 'instagram_reels'],
  },
  {
    id: 'T02',
    rank: 2,
    name: 'Space & Astronomy (NASA Footage)',
    triggers: ['awe'],
    ia_queries: ['NASA space rocket launch footage', 'hubble james webb telescope galaxy', 'ISS earth timelapse astronaut spacewalk', 'mars moon planet exploration'],
    stock_queries: ['space cosmos universe stars', 'earth from space galaxy milky way', 'planet nebula rocket launch'],
    mediatype: 'movies',
    music_genre: 'Ambient electronic, epic orchestral, lo-fi space beats',
    caption_strategy: 'Mind-blowing scale facts ("This galaxy is 2 million light-years away") + timestamp',
    platform_priority: ['youtube_shorts', 'tiktok', 'instagram_reels'],
  },
  {
    id: 'T03',
    rank: 3,
    name: 'Historical Moments & Archival Footage',
    triggers: ['nostalgia', 'awe', 'shock'],
    ia_queries: ['historical newsreel 1940s 1950s 1960s', 'world war II archive footage', 'moon landing apollo 1969', 'berlin wall cold war historical event'],
    mediatype: 'movies',
    ia_collection: 'prelinger',
    music_genre: 'Period-appropriate public domain classical, cinematic score, emotional piano',
    caption_strategy: 'Year + location + one-line context ("Berlin, November 9, 1989 — the wall falls")',
    platform_priority: ['youtube_shorts', 'tiktok', 'instagram_reels'],
  },
  {
    id: 'T04',
    rank: 4,
    name: 'Extreme Weather & Natural Disasters',
    triggers: ['shock', 'awe'],
    ia_queries: ['tornado hurricane extreme weather footage', 'volcanic eruption lava disaster', 'tsunami flood earthquake disaster footage', 'lightning storm blizzard severe weather'],
    mediatype: 'movies',
    music_genre: 'Dramatic orchestral, tension-building electronic, bass-heavy cinematic',
    caption_strategy: 'Scale data overlay ("Wind speed: 200 mph / Category 5") + location + date',
    platform_priority: ['tiktok', 'instagram_reels', 'youtube_shorts'],
  },
  {
    id: 'T05',
    rank: 5,
    name: 'Classic Cartoons (Public Domain Animation)',
    triggers: ['nostalgia', 'amusement'],
    ia_queries: ['charlie chaplin buster keaton silent film comedy', 'betty boop popeye fleischer animation', 'felix cat steamboat willie public domain cartoon', 'vintage animation 1930s 1940s'],
    mediatype: 'movies',
    ia_collection: 'animationandcartoons',
    music_genre: 'Phonk, trap, lo-fi hip-hop, modern pop remixes',
    caption_strategy: 'Humorous modern commentary overlaid on vintage action ("POV: it\'s 1928 and you just invented violence")',
    platform_priority: ['tiktok', 'instagram_reels', 'youtube_shorts'],
  },
  {
    id: 'T06',
    rank: 6,
    name: 'Human Physical Feats & World Records',
    triggers: ['awe', 'inspiration'],
    ia_queries: ['world record athlete sports achievement', 'olympic gymnastics athletics performance', 'extreme sport world record breaking moment', 'superhuman physical feat strength speed'],
    mediatype: 'movies',
    music_genre: 'Energetic trap, motivational hip-hop, epic orchestral',
    caption_strategy: 'Record stat overlay ("World Record: 9.58 seconds") + athlete name + year',
    platform_priority: ['tiktok', 'instagram_reels', 'youtube_shorts'],
  },
  {
    id: 'T07',
    rank: 7,
    name: 'Science Experiments & Unexpected Physical Phenomena',
    triggers: ['awe', 'curiosity'],
    ia_queries: ['science experiment chemistry physics reaction', 'slow motion explosion fire chemical', 'magnetic phenomena non-newtonian fluid', 'university science educational demonstration'],
    mediatype: 'movies',
    music_genre: 'Electronic, glitch, ambient, lo-fi',
    caption_strategy: 'Question hook ("What happens when you mix gallium and aluminum?") + answer reveal at end',
    platform_priority: ['tiktok', 'youtube_shorts', 'instagram_reels'],
  },
  {
    id: 'T08',
    rank: 8,
    name: 'Optical Illusions & Mind-Bending Visuals',
    triggers: ['curiosity', 'shock'],
    ia_queries: ['optical illusion mind trick visual perception', 'impossible figure ambiguous image illusion', 'motion illusion animation perceptual', 'visual paradox trick eye'],
    mediatype: 'movies',
    music_genre: 'Mysterious ambient, glitch electronic, suspenseful lo-fi',
    caption_strategy: 'Challenge hook ("Only 1% of people can see this correctly") + answer reveal',
    platform_priority: ['tiktok', 'instagram_reels', 'youtube_shorts'],
  },
  {
    id: 'T09',
    rank: 9,
    name: 'Motivational Speeches Over Cinematic Footage',
    triggers: ['inspiration', 'awe'],
    ia_queries: ['motivational speech inspiration JFK Churchill historical', 'commencement speech graduation motivation', 'historical speech public domain audio', 'underdog victory speech inspiration'],
    mediatype: 'movies',
    music_genre: 'Epic orchestral, emotional piano, cinematic score',
    caption_strategy: 'Key quote in large bold text, timed to speech rhythm',
    platform_priority: ['youtube_shorts', 'tiktok', 'instagram_reels'],
  },
  {
    id: 'T10',
    rank: 10,
    name: 'Animal Babies & Cute Pet Moments',
    triggers: ['amusement', 'awe'],
    ia_queries: ['baby animals cute puppy kitten footage', 'pygmy hippo penguin chick baby zoo', 'pet compilation cute animal funny', 'wildlife baby animal nature documentary'],
    mediatype: 'movies',
    music_genre: 'Upbeat acoustic, cheerful ukulele, playful lo-fi',
    caption_strategy: 'Personality-driven text ("Me on Monday morning" over sleepy kitten) + species fact overlay',
    platform_priority: ['tiktok', 'instagram_reels', 'youtube_shorts'],
  },
  {
    id: 'T11',
    rank: 11,
    name: 'True Crime & Unsolved Mysteries (Narrated)',
    triggers: ['curiosity', 'shock'],
    ia_queries: ['true crime mystery unsolved murder documentary', 'criminal investigation court footage archive', 'cold case mystery historical crime newsreel', 'detective investigation mystery documentary'],
    mediatype: 'movies',
    music_genre: 'Dark ambient, suspenseful strings, lo-fi horror',
    caption_strategy: 'Open loop hook ("This case was never solved. Here\'s why.") + chapter-style text overlays',
    platform_priority: ['youtube_shorts', 'tiktok', 'instagram_reels'],
  },
  {
    id: 'T12',
    rank: 12,
    name: 'Vintage Fails & Slapstick Comedy (Archival)',
    triggers: ['amusement'],
    ia_queries: ['charlie chaplin buster keaton harold lloyd comedy', 'slapstick comedy falls fails vintage 1920s 1930s', 'silent film comedy physical humor public domain', 'vintage physical comedy pratfall stunt'],
    mediatype: 'movies',
    music_genre: 'Modern trap, phonk, comedy sound effects royalty-free, lo-fi',
    caption_strategy: 'Modern slang overlay on vintage action ("He said \'hold my beer\' in 1923")',
    platform_priority: ['tiktok', 'instagram_reels', 'youtube_shorts'],
  },
  {
    id: 'T13',
    rank: 13,
    name: 'Time-Lapse & Hyperlapse (Nature, Cities, Sky)',
    triggers: ['awe'],
    ia_queries: ['timelapse nature sunrise sunset clouds', 'city timelapse urban night stars', 'flower blooming storm forming timelapse', 'ISS earth timelapse NASA space station'],
    mediatype: 'movies',
    music_genre: 'Ambient electronic, lo-fi beats, cinematic score',
    caption_strategy: 'Minimal — location + time span ("Tokyo, 24 hours in 30 seconds")',
    platform_priority: ['instagram_reels', 'tiktok', 'youtube_shorts'],
  },
  {
    id: 'T14',
    rank: 14,
    name: 'Restoration & Transformation (Before/After)',
    triggers: ['awe', 'satisfaction'],
    ia_queries: ['restoration transformation before after footage', 'building restoration renovation before after', 'colorized historical footage restoration AI', 'object restoration cleaning before after'],
    mediatype: 'movies',
    music_genre: 'Satisfying lo-fi, uplifting acoustic, gentle electronic',
    caption_strategy: 'Progress indicator overlay + final reveal text',
    platform_priority: ['tiktok', 'instagram_reels', 'youtube_shorts'],
  },
  {
    id: 'T15',
    rank: 15,
    name: 'Space Exploration Milestones (Narrated)',
    triggers: ['awe', 'inspiration'],
    ia_queries: ['apollo moon landing NASA 1969 milestone', 'mars rover landing spacex voyager probe', 'james webb telescope discovery space milestone', 'space shuttle launch landing historic NASA'],
    mediatype: 'movies',
    music_genre: 'Epic orchestral, ambient space music, emotional piano',
    caption_strategy: 'Countdown/timeline overlay + key quote from astronauts',
    platform_priority: ['youtube_shorts', 'tiktok', 'instagram_reels'],
  },
  {
    id: 'T16',
    rank: 16,
    name: 'Underwater & Ocean Life',
    triggers: ['awe', 'curiosity'],
    ia_queries: ['underwater ocean deep sea footage NOAA', 'coral reef marine life bioluminescent', 'whale shark dolphin ocean encounter footage', 'deep sea creature submarine exploration'],
    mediatype: 'movies',
    music_genre: 'Ambient underwater sounds, ethereal electronic, lo-fi',
    caption_strategy: 'Depth/pressure data overlay + creature name + fun fact',
    platform_priority: ['tiktok', 'instagram_reels', 'youtube_shorts'],
  },
  {
    id: 'T17',
    rank: 17,
    name: 'Historical "What If" & Counterfactual Scenarios',
    triggers: ['curiosity', 'debate'],
    ia_queries: ['world war II historical documentary archive footage', 'cold war nuclear historical tension footage', 'historical turning point archive documentary', 'WWII D-Day Berlin liberation historical newsreel'],
    mediatype: 'movies',
    ia_collection: 'prelinger',
    music_genre: 'Cinematic score, dramatic orchestral',
    caption_strategy: 'Bold question hook + chapter-style argument text',
    platform_priority: ['youtube_shorts', 'tiktok'],
  },
  {
    id: 'T18',
    rank: 18,
    name: 'Vintage Advertising & Cultural Artifacts',
    triggers: ['nostalgia', 'amusement'],
    ia_queries: ['vintage advertisement commercial 1950s 1960s', 'retro educational film public information 1950s', 'industrial promotional film vintage ephemeral', 'cold war era educational government film'],
    mediatype: 'movies',
    ia_collection: 'prelinger',
    music_genre: 'Retro synth, lo-fi, modern pop contrast',
    caption_strategy: 'Modern commentary overlay ("1950s safety video hits different in 2025")',
    platform_priority: ['tiktok', 'instagram_reels'],
  },
  {
    id: 'T19',
    rank: 19,
    name: 'Extreme Sports & Stunts (CC-Licensed)',
    triggers: ['awe', 'shock'],
    ia_queries: ['extreme sport skydiving base jump footage', 'free solo climbing skiing snowboarding stunt', 'POV extreme sport gopro action footage', 'wingsuit paragliding extreme aerial footage'],
    mediatype: 'movies',
    music_genre: 'Energetic electronic, trap, phonk, drum and bass',
    caption_strategy: 'Speed/altitude data overlay + POV text ("2,000 meters above the Alps")',
    platform_priority: ['tiktok', 'instagram_reels', 'youtube_shorts'],
  },
  {
    id: 'T20',
    rank: 20,
    name: 'Satisfying Processes & ASMR-Adjacent Footage',
    triggers: ['satisfaction'],
    ia_queries: ['glassblowing pottery craft process satisfying', 'metal casting woodworking craft making', 'cake decorating food making process satisfying', 'industrial manufacturing process craftsmanship'],
    mediatype: 'movies',
    music_genre: 'Soft lo-fi, gentle ASMR sounds, ambient',
    caption_strategy: 'Process name + material + time ("Hand-blown glass / 1,400°C / 4 minutes")',
    platform_priority: ['tiktok', 'instagram_reels', 'youtube_shorts'],
  },
  {
    id: 'T21',
    rank: 21,
    name: 'Colorized Historical Footage',
    triggers: ['nostalgia', 'awe'],
    ia_queries: ['colorized historical black white footage WWI WWII', 'vintage 1920s 1930s daily life archival film', 'colorized silent era historical footage', 'early 20th century life documentary archive'],
    mediatype: 'movies',
    ia_collection: 'prelinger',
    music_genre: 'Period-appropriate public domain classical, emotional orchestral',
    caption_strategy: 'Year + location + "Colorized with AI" disclosure',
    platform_priority: ['tiktok', 'youtube_shorts', 'instagram_reels'],
  },
  {
    id: 'T22',
    rank: 22,
    name: 'Geopolitical & Social Change Moments',
    triggers: ['shock', 'inspiration'],
    ia_queries: ['berlin wall fall 1989 historical footage', 'civil rights movement protest march archive', 'revolution social change historical newsreel', 'geopolitical historic event archive documentary'],
    mediatype: 'movies',
    music_genre: 'Cinematic orchestral, emotional piano',
    caption_strategy: 'Date + location + historical significance ("November 9, 1989 — 28 years of division end")',
    platform_priority: ['youtube_shorts', 'tiktok'],
  },
  {
    id: 'T23',
    rank: 23,
    name: 'Microscopy & Macro Photography (Invisible World)',
    triggers: ['awe', 'curiosity'],
    ia_queries: ['microscope cell division bacteria microscopy footage', 'macro insect photography extreme close-up', 'crystal formation microscopy time-lapse', 'electron microscope biology educational footage'],
    mediatype: 'movies',
    music_genre: 'Ambient electronic, ethereal, lo-fi',
    caption_strategy: 'Scale indicator ("This is 1,000x magnification") + organism/process name',
    platform_priority: ['tiktok', 'youtube_shorts', 'instagram_reels'],
  },
  {
    id: 'T24',
    rank: 24,
    name: '"Did You Know?" Facts With Archival Proof',
    triggers: ['curiosity'],
    ia_queries: ['educational documentary science facts archive', 'historical curiosity unusual fact footage', 'science nature documentary surprising facts', 'archival footage unusual historical fact'],
    mediatype: 'movies',
    music_genre: 'Curious lo-fi, light electronic, upbeat acoustic',
    caption_strategy: 'Bold fact statement + source citation + "Share if you didn\'t know this"',
    platform_priority: ['tiktok', 'youtube_shorts', 'instagram_reels'],
  },
  {
    id: 'T25',
    rank: 25,
    name: 'Classic Literature & Poetry Visualized',
    triggers: ['inspiration', 'nostalgia'],
    ia_queries: ['shakespeare dickens poetry public domain reading', 'classic literature spoken word public domain', 'stoicism philosophy life lessons reading', 'edgar allan poe whitman twain reading audio'],
    mediatype: 'audio',
    music_genre: 'Classical piano public domain compositions, ambient, emotional orchestral',
    caption_strategy: 'Quote in large serif font + author attribution',
    platform_priority: ['instagram_reels', 'tiktok', 'youtube_shorts'],
  },
  {
    id: 'T26',
    rank: 26,
    name: 'Timelapse of Urban Development & Architecture',
    triggers: ['awe', 'curiosity'],
    ia_queries: ['city urban development timelapse architecture', 'construction building growth urban timelapse', 'historical city transformation before after footage', 'skyline urban architecture documentary archive'],
    mediatype: 'movies',
    music_genre: 'Cinematic orchestral, ambient electronic, lo-fi',
    caption_strategy: 'Year-by-year overlay + city name + population data',
    platform_priority: ['youtube_shorts', 'tiktok', 'instagram_reels'],
  },
  {
    id: 'T27',
    rank: 27,
    name: 'Rare & Extinct Animal Footage',
    triggers: ['awe', 'curiosity'],
    ia_queries: ['extinct animal thylacine tasmanian tiger footage', 'rare endangered species wildlife footage archive', 'passenger pigeon dodo extinct animal historical', 'critically endangered wildlife last footage'],
    mediatype: 'movies',
    music_genre: 'Melancholic piano, ambient, emotional orchestral',
    caption_strategy: 'Species name + last known date + extinction cause',
    platform_priority: ['tiktok', 'youtube_shorts', 'instagram_reels'],
    min_score: 20,
  },
  {
    id: 'T28',
    rank: 28,
    name: 'Speed Runs & Skill Demonstrations',
    triggers: ['awe', 'amusement'],
    ia_queries: ['speed chess rubik cube solving world record', 'speed skill demonstration typing drawing rapid', 'speedrun record breaking game skill footage', 'rapid skill demonstration talent performance'],
    mediatype: 'movies',
    music_genre: 'Upbeat electronic, energetic trap, fast-tempo lo-fi',
    caption_strategy: 'Speed stat overlay ("Solved in 3.47 seconds") + challenge hook',
    platform_priority: ['tiktok', 'instagram_reels', 'youtube_shorts'],
  },
  {
    id: 'T29',
    rank: 29,
    name: 'Vintage Music Performances (Public Domain)',
    triggers: ['nostalgia', 'amusement'],
    ia_queries: ['jazz blues vintage performance 1920s 1930s public domain', 'early jazz big band swing music performance archive', 'vintage blues folk music recording performance', 'pre-war music performance public domain recording'],
    mediatype: 'movies',
    music_genre: 'The original recording itself, remixed or modernized',
    caption_strategy: 'Artist name + year + "This was recorded before your grandparents were born"',
    platform_priority: ['tiktok', 'instagram_reels'],
  },
  {
    id: 'T30',
    rank: 30,
    name: 'AI-Enhanced & Upscaled Historical Footage',
    triggers: ['awe', 'nostalgia'],
    ia_queries: ['historical footage upscale restore 4K archive', 'vintage film restoration colorized upscaled', 'early cinema 1900s 1910s historical footage', 'silent era historical film archive public domain'],
    mediatype: 'movies',
    ia_collection: 'prelinger',
    music_genre: 'Cinematic orchestral, ambient, period-appropriate',
    caption_strategy: '"Restored to 4K with AI" + year + location',
    platform_priority: ['youtube_shorts', 'tiktok', 'instagram_reels'],
  },
];

export const TOP_10_TOPICS: TopicConfig[] = VIRAL_TOPICS.slice(0, 10);
