/**
 * cto-approval-gate.ts — CTO Sprint Approval Gate
 *
 * MANDATORY: Every sprint plan generated by the autonomous loop MUST be
 * reviewed and approved by the CTO agent before execution begins.
 *
 * The CTO checks:
 *   1. Is this sprint in the execution plan? (FULL_WORK_PLAN.md / PHASE_1_EXECUTION_PLAN.md)
 *   2. Does it advance the current phase gate?
 *   3. Is it a Sev-1 fix or critical path item?
 *   4. Does it duplicate work already completed?
 *
 * If the CTO rejects, the sprint is logged and skipped.
 * If the CTO approves, execution proceeds normally.
 *
 * This prevents the autonomous swarm from inventing its own work.
 *
 * @see ClawRouter Spec v2.0 — CTO agent uses T2 POWER (qwen3:14b) for review
 */

import * as fs from 'fs';
import * as path from 'path';
import { routeCall, type ClawRouterV2Response } from './clawrouter-v2';
import { checkCapability, getAgent, type Capability, type CapabilityCheckResult } from '../../agents/lib/acp';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface SprintProposal {
  sprint_id: string;
  title: string;
  description: string;
  tasks: string[];
  estimated_complexity: string;
  source: 'autonomous_loop' | 'human' | 'cto_backlog';
  /** Optional: map of agent_id → required capabilities for ACP pre-check */
  agent_capabilities?: Array<{ agent: string; required_capabilities: Capability[] }>;
}

export interface CTOApprovalResult {
  approved: boolean;
  sprint_id: string;
  reason: string;
  plan_reference: string;    // which plan item this maps to (or "NOT_IN_PLAN")
  cto_confidence: number;    // 0-100
  timestamp: string;
  acp_violations?: CapabilityCheckResult[];  // Sprint 650: ACP pre-check violations
}

// ── Plan Context Loader ───────────────────────────────────────────────────────

function loadPlanContext(projectRoot: string): string {
  const planFiles = [
    path.join(projectRoot, '..', 'Documents', 'Kognai', 'plans', 'PHASE_1_EXECUTION_PLAN.md'),
    path.join(projectRoot, '..', 'Documents', 'Kognai', 'plans', 'FULL_WORK_PLAN.md'),
  ];

  let context = '';
  for (const f of planFiles) {
    try {
      if (fs.existsSync(f)) {
        const content = fs.readFileSync(f, 'utf-8');
        // Take first 3000 chars of each plan file (QCG budget)
        context += `\n--- ${path.basename(f)} ---\n${content.slice(0, 3000)}\n`;
      }
    } catch { /* skip */ }
  }

  // Also load recent sprint files to check for duplicates
  const sprintsDir = path.join(projectRoot, 'sprints');
  if (fs.existsSync(sprintsDir)) {
    try {
      const recent = fs.readdirSync(sprintsDir)
        .filter(f => f.endsWith('.json'))
        .sort()
        .slice(-10); // last 10 sprints
      const titles = recent.map(f => {
        try {
          const data = JSON.parse(fs.readFileSync(path.join(sprintsDir, f), 'utf-8'));
          return `${f}: ${data.title || data.name || 'untitled'}`;
        } catch { return f; }
      });
      context += `\n--- Recent Sprints (last 10) ---\n${titles.join('\n')}\n`;
    } catch { /* skip */ }
  }

  return context;
}

// ── CTO Review ────────────────────────────────────────────────────────────────

/**
 * Submit a sprint proposal to the CTO agent for approval.
 * Returns approval/rejection with reasoning.
 *
 * Uses T2 POWER (qwen3:14b, local, $0) for the review.
 */
export async function requestCTOApproval(
  proposal: SprintProposal,
  projectRoot: string,
  product: 'kognai' | 'invoica' = 'kognai'
): Promise<CTOApprovalResult> {
  const timestamp = new Date().toISOString();

  // Human-submitted sprints bypass CTO gate
  if (proposal.source === 'human') {
    return {
      approved: true,
      sprint_id: proposal.sprint_id,
      reason: 'Human-submitted sprint — auto-approved per governance rules.',
      plan_reference: 'HUMAN_OVERRIDE',
      cto_confidence: 100,
      timestamp,
    };
  }

  // Sprint 650: ACP pre-check — reject if agents lack required capabilities
  if (proposal.agent_capabilities && proposal.agent_capabilities.length > 0) {
    const violations: CapabilityCheckResult[] = [];
    for (const task of proposal.agent_capabilities) {
      for (const cap of task.required_capabilities) {
        const result = checkCapability(task.agent, cap);
        if (!result.allowed) violations.push(result);
      }
    }
    if (violations.length > 0) {
      const violationSummary = violations.map(v => `${v.agent_id}: ${v.reason}`).join('; ');
      return {
        approved: false,
        sprint_id: proposal.sprint_id,
        reason: `ACP violation: ${violationSummary}`,
        plan_reference: 'ACP_VIOLATION',
        cto_confidence: 100,
        timestamp,
        acp_violations: violations,
      };
    }
  }

  const planContext = loadPlanContext(projectRoot);

  const systemPrompt = `You are the CTO agent for ${product}. Your ONLY job is to decide whether a proposed sprint should be executed or rejected.

RULES:
1. APPROVE if the sprint directly maps to an item in the execution plan or work plan
2. APPROVE if the sprint is a Sev-1 bug fix or critical path blocker fix
3. REJECT if the sprint is not in any plan and is not a critical fix
4. REJECT if the sprint duplicates work already completed in recent sprints
5. REJECT if the sprint invents new features not requested by the human founder

You must respond ONLY with valid JSON:
{
  "approved": true/false,
  "reason": "one sentence explanation",
  "plan_reference": "which plan item this maps to, or NOT_IN_PLAN",
  "confidence": 0-100
}`;

  const prompt = `SPRINT PROPOSAL:
ID: ${proposal.sprint_id}
Title: ${proposal.title}
Description: ${proposal.description}
Tasks: ${proposal.tasks.join('; ')}
Source: ${proposal.source}

CURRENT PLANS AND RECENT SPRINTS:
${planContext}

Should this sprint be approved or rejected? Respond with JSON only.`;

  try {
    const response = await routeCall({
      task_type: 'cto_sprint_review',
      tier_class: 'text',
      complexity: 'power',      // T2 — local, $0
      context_tokens: Math.ceil((prompt.length + systemPrompt.length) / 4),
      constitutional_flag: false,
      agent_id: `cto-${product}`,
      payload: { system: systemPrompt, prompt, max_tokens: 500 },
    });

    // Parse CTO response
    const content = response.content.trim();
    // Extract JSON from response (handle markdown code blocks)
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      // If CTO can't parse → reject by default (safe side)
      return {
        approved: false,
        sprint_id: proposal.sprint_id,
        reason: 'CTO response was not valid JSON — rejecting for safety.',
        plan_reference: 'PARSE_ERROR',
        cto_confidence: 0,
        timestamp,
      };
    }

    const parsed = JSON.parse(jsonMatch[0]);
    const result: CTOApprovalResult = {
      approved: Boolean(parsed.approved),
      sprint_id: proposal.sprint_id,
      reason: String(parsed.reason || 'No reason given'),
      plan_reference: String(parsed.plan_reference || 'UNKNOWN'),
      cto_confidence: Number(parsed.confidence) || 0,
      timestamp,
    };

    // Log the decision
    logCTODecision(result, projectRoot, product);

    return result;

  } catch (err: any) {
    // If CTO agent is unavailable → reject by default
    return {
      approved: false,
      sprint_id: proposal.sprint_id,
      reason: `CTO agent unavailable: ${err.message}. Rejecting for safety.`,
      plan_reference: 'CTO_UNAVAILABLE',
      cto_confidence: 0,
      timestamp,
    };
  }
}

// ── Decision Log ──────────────────────────────────────────────────────────────

function logCTODecision(result: CTOApprovalResult, projectRoot: string, product: string): void {
  try {
    const logDir = path.join(projectRoot, 'logs', 'cto-gate');
    if (!fs.existsSync(logDir)) fs.mkdirSync(logDir, { recursive: true });
    const logFile = path.join(logDir, `${result.timestamp.slice(0, 10)}.jsonl`);
    fs.appendFileSync(logFile, JSON.stringify({ product, ...result }) + '\n');
  } catch { /* non-critical */ }
}

// ── Batch Review (for autonomous loop) ────────────────────────────────────────

/**
 * Review multiple sprint proposals in sequence. Returns only approved ones.
 * Use this in the autonomous loop to filter proposals before execution.
 */
export async function batchCTOReview(
  proposals: SprintProposal[],
  projectRoot: string,
  product: 'kognai' | 'invoica' = 'kognai'
): Promise<{ approved: SprintProposal[]; rejected: CTOApprovalResult[] }> {
  const approved: SprintProposal[] = [];
  const rejected: CTOApprovalResult[] = [];

  for (const proposal of proposals) {
    const result = await requestCTOApproval(proposal, projectRoot, product);
    if (result.approved) {
      approved.push(proposal);
    } else {
      rejected.push(result);
    }
  }

  return { approved, rejected };
}
