#!/bin/bash
# setup-mission-control.sh — One-time setup for Mission Control on Hetzner
#
# Run this ONCE on the server:
#   bash /home/invoica/apps/Invoica/scripts/setup-mission-control.sh
#
# What it does:
#   1. Clones builderz-labs/mission-control to /home/invoica/apps/mission-control
#   2. Installs pnpm + dependencies
#   3. Creates .env with credentials (auto-generates if not already set)
#   4. Builds the Next.js app (~1-2 min)
#   5. Appends MC credentials to Invoica .env so agents can connect
#   6. Prints instructions for accessing the dashboard
#
# After this script:
#   - PM2 will pick up the mission-control process on the next autodeploy
#   - Access via SSH tunnel: ssh -L 3010:localhost:3010 invoica@<server>
#   - Or via direct IP: http://<server-ip>:3010 (requires port 3010 to be open)

set -euo pipefail

MC_DIR="/home/invoica/apps/mission-control"
MC_DATA_DIR="/home/invoica/mission-control-data"
INVOICA_DIR="/home/invoica/apps/Invoica"
NODE_BIN_DIR="/home/invoica/.nodejs/bin"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "[$TIMESTAMP] === Mission Control Setup ==="
echo ""

# ── 1. Check Node.js ────────────────────────────────────────────────────────
if ! command -v node &>/dev/null; then
  export PATH="$NODE_BIN_DIR:$PATH"
fi
NODE_VER=$(node --version 2>/dev/null || echo "not found")
echo "[MC] Node.js: $NODE_VER"
if [[ "$NODE_VER" == "not found" ]]; then
  echo "[MC] ERROR: Node.js not found. Cannot continue."
  exit 1
fi

# ── 2. Install pnpm globally if not present ──────────────────────────────────
export PATH="$NODE_BIN_DIR:$PATH"
if ! command -v pnpm &>/dev/null; then
  echo "[MC] Installing pnpm globally..."
  npm install -g pnpm
  echo "[MC] pnpm installed: $(pnpm --version)"
else
  echo "[MC] pnpm: $(pnpm --version)"
fi

# ── 3. Clone or update repo ──────────────────────────────────────────────────
if [ -d "$MC_DIR/.git" ]; then
  echo "[MC] Updating existing clone at $MC_DIR..."
  cd "$MC_DIR"
  git pull origin main --quiet
  echo "[MC] Updated to $(git rev-parse --short HEAD)"
else
  echo "[MC] Cloning mission-control..."
  git clone https://github.com/builderz-labs/mission-control.git "$MC_DIR"
  cd "$MC_DIR"
  echo "[MC] Cloned at $(git rev-parse --short HEAD)"
fi

# ── 4. Create data directory ─────────────────────────────────────────────────
mkdir -p "$MC_DATA_DIR"
echo "[MC] Data dir: $MC_DATA_DIR"

# ── 5. Generate credentials (or reuse from Invoica .env) ────────────────────
# Source Invoica .env to pick up any existing MC credentials
if [ -f "$INVOICA_DIR/.env" ]; then
  set -a
  source "$INVOICA_DIR/.env" 2>/dev/null || true
  set +a
fi

MC_AUTH_PASS="${MC_AUTH_PASS:-$(openssl rand -base64 16 | tr -d '=+/' | head -c 16)}"
MC_API_KEY="${MC_API_KEY:-mc-$(openssl rand -hex 16)}"
MC_PORT="${MC_PORT:-3010}"

# ── 6. Create Mission Control .env ───────────────────────────────────────────
echo "[MC] Writing $MC_DIR/.env..."
cat > "$MC_DIR/.env" << EOF
# Mission Control — generated by Invoica setup-mission-control.sh
# Generated: $TIMESTAMP

# Admin login
AUTH_USER=admin
AUTH_PASS=$MC_AUTH_PASS

# API key for agent connections (used by Invoica agent scripts)
API_KEY=$MC_API_KEY

# OpenClaw gateway (runs on the same server)
# Find the port in /opt/oc/ config files if 3002 is wrong
OPENCLAW_HOST=localhost
OPENCLAW_PORT=${OPENCLAW_PORT:-3002}
OPENCLAW_TOKEN=${OPENCLAW_TOKEN:-}

# Server
PORT=$MC_PORT
NODE_ENV=production

# Storage
DATA_DIR=$MC_DATA_DIR

# Network — allow access from any host (use nginx/Caddy for TLS if needed)
MC_ALLOW_ANY_HOST=1
EOF

echo "[MC] .env created"

# ── 7. Install dependencies ──────────────────────────────────────────────────
echo "[MC] Installing dependencies (this may take 30-60s)..."
cd "$MC_DIR"
pnpm install --frozen-lockfile 2>/dev/null || pnpm install
echo "[MC] Dependencies installed"

# ── 8. Build ─────────────────────────────────────────────────────────────────
echo "[MC] Building Next.js app (this takes ~1-2 minutes)..."
pnpm build
echo "[MC] Build complete"

# ── 8b. Copy static assets into standalone dir (required for standalone builds) ─
# Next.js standalone server.js does NOT serve /_next/static or /public by itself
if [ -d ".next/standalone" ]; then
  echo "[MC] Copying static assets to standalone dir..."
  cp -r .next/static .next/standalone/.next/static
  cp -r public      .next/standalone/public 2>/dev/null || true
  echo "[MC] Static assets copied"
fi

# ── 9. Add MC credentials to Invoica .env so agents can auto-connect ─────────
if [ -f "$INVOICA_DIR/.env" ]; then
  # Remove any existing MC lines to avoid duplicates
  grep -v "^MC_API_KEY=\|^MC_AUTH_PASS=\|^MC_PORT=\|^MC_BASE_URL=\|^# Mission Control" \
    "$INVOICA_DIR/.env" > /tmp/invoica-env-tmp && mv /tmp/invoica-env-tmp "$INVOICA_DIR/.env"

  # Append fresh values
  cat >> "$INVOICA_DIR/.env" << EOF

# Mission Control — agent dashboard (http://localhost:$MC_PORT)
MC_API_KEY=$MC_API_KEY
MC_AUTH_PASS=$MC_AUTH_PASS
MC_PORT=$MC_PORT
MC_BASE_URL=http://localhost:$MC_PORT
EOF
  echo "[MC] Appended MC credentials to $INVOICA_DIR/.env"
fi

# ── 10. Summary ───────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           ✅  Mission Control Setup Complete                 ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  Dashboard URL : http://localhost:$MC_PORT"
echo "  Admin user    : admin"
echo "  Admin password: $MC_AUTH_PASS"
echo "  API key       : $MC_API_KEY"
echo ""
echo "  Access options:"
echo "  • SSH tunnel : ssh -L $MC_PORT:localhost:$MC_PORT user@<server-ip>"
echo "    then open: http://localhost:$MC_PORT"
echo "  • Direct IP  : http://<server-ip>:$MC_PORT (open port $MC_PORT in firewall)"
echo ""
echo "  PM2 will start mission-control within 5 minutes (next autodeploy cycle)."
echo "  Or start manually: pm2 restart mission-control"
echo ""
echo "  Agents will start reporting to Mission Control automatically."
echo ""
